name: Promote Fix

on:
  workflow_dispatch:
    inputs:
      fix_branch:
        description: 'Full fix branch (e.g. skyscanner-internal/releases/v2.14.9/fix-issue-123)'
        required: true
        type: string
      proposal_branch:
        description: 'Name under skyscanner-contrib/proposal/ (e.g. fix-issue-123)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repo (branches & tags)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'

      - name: Invoke promote-fix
        run: |
          go run tools/fork-cli/main.go promote-fix \
            --fix-branch="${{ inputs.fix_branch }}" \
            --proposal-branch="${{ inputs.proposal_branch }}"
