name: Sync Fork

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual sync'
        required: false
        default: 'Manual trigger'
  
  # Schedule to run at 10:00 UTC every day
  schedule:
    - cron: '0 10 * * *'

jobs:
  sync-fork:
    name: Sync Fork with Upstream
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for pushing branches
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full git history for proper rebasing

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Fetch all branches
        run: |
          # Ensure we have both forks
          git fetch --all
          git fetch origin skyscanner-contrib/master:skyscanner-contrib/master

      - name: Run fork sync
        id: sync
        run: |
          echo "::group::Fork Sync Output"
          go run tools/fork-cli/main.go sync-fork
          echo "::endgroup::"

      - name: Sync success notification
        if: ${{ success() }}
        run: |
          echo "✅ Fork sync completed successfully!"
          echo "• skyscanner-contrib/master is synced with upstream/master"
          echo "• skyscanner-internal/master is synced with skyscanner-contrib/master"
          
      - name: Sync failure notification
        if: ${{ failure() }}
        run: |
          echo "❌ Fork sync failed! A manual intervention is required."
          echo "One of the following issues may have occurred:"
          echo "• IP allow list restrictions preventing GitHub Actions from pushing"
          echo "• Merge conflicts that need manual resolution"
          echo "• Network or authentication issues"
          echo ""
          echo "Please run the sync-fork command locally to resolve conflicts:"
          echo "  go run tools/fork-cli/main.go sync-fork"